require:
  - rubocop-rails

inherit_from:
 - ./private/rspec.yml
 - ./private/standard.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRailsVersion: 5.2

# Place custom configuration for rubocop-rails cops here